In [7]:
import numpy as np

In [9]:
X = np.random.normal(loc=1, scale=10, size=(1000,50))
print (X)

[[  7.51623208 -15.51994973 -11.69562839 ...  10.5419197   12.03096729
  -13.50868857]
 [ -4.44779405  -4.40312206   3.70528541 ...  12.12794422  -8.63321038
   15.75548731]
 [ -2.87017221   1.40693426   9.33776163 ...  -2.77861318   1.81518707
  -10.1583185 ]
 ...
 [  9.04930825   0.57396567   0.05614564 ... -11.23973581 -11.45751323
   -2.47873066]
 [ 13.70330674  -9.78694539  -1.13066737 ...  15.38674393   0.67294951
  -10.99488944]
 [ -8.1701711    6.93435249  18.341057   ...   0.15093749  -1.33700221
   13.52175582]]


In [10]:
m = np.mean(X, axis=0)
std = np.std(X, axis=0)
X_norm  = ((X - m) / std)
print (X_norm)

[[ 0.63483923 -1.68227671 -1.24090861 ...  0.93100739  1.11477292
  -1.4631233 ]
 [-0.60167891 -0.54049151  0.27784749 ...  1.08719    -0.95589034
   1.47476646]
 [-0.43862694  0.05624674  0.8332923  ... -0.38072241  0.09109605
  -1.12677288]
 ...
 [ 0.79328727 -0.02930566 -0.08201124 ... -1.21392532 -1.23890088
  -0.35580353]
 [ 1.27429203 -1.0934523  -0.19904842 ...  1.40809793 -0.02336238
  -1.21075792]
 [-0.98639779  0.62395584  1.72114935 ... -0.09223704 -0.2247705
   1.25051764]]


In [11]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])

In [12]:
r = np.sum(Z, axis=1)
print (np.nonzero(r > 10))

(array([1, 4, 5], dtype=int64),)


In [16]:
A = np.eye(3)
B = np.eye(3)
AB = np.vstack((A, B))
print (AB)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
import pandas as pd

In [46]:
data = pd.read_csv('titanic.csv', index_col = 'PassengerId')

In [57]:
data.head(50)

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   
6                   0       3   
7                   0       1   
8                   0       3   
9                   1       3   
10                  1       2   
11                  1       3   
12                  1       1   
13                  0       3   
14                  0       3   
15                  0       3   
16                  1       2   
17                  0       3   
18                  1       2   
19                  0       3   
20                  1       3   
21                  0       2   
22                  1       2   
23                  1       3   
24                  1       1   
25                  0       3   
26                  1       3   
27                  0       3   
28                  0       1   
29                  1       3   
30                  0       3   
31                  0       1   
32                  1       1   
33                  1       3   
34                  0       2   
35                  0       1   
36                  0       1   
37                  1       3   
38                  0       3   
39                  0       3   
40                  1       3   
41                  0       3   
42                  0       2   
43                  0       3   
44                  1       2   
45                  1       3   
46                  0       3   
47                  0       3   
48                  1       3   
49                  0       3   
50                  0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   
6                                             Moran, Mr. James    male   NaN   
7                                      McCarthy, Mr. Timothy J    male  54.0   
8                               Palsson, Master. Gosta Leonard    male   2.0   
9            Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0   
10                         Nasser, Mrs. Nicholas (Adele Achem)  female  14.0   
11                             Sandstrom, Miss. Marguerite Rut  female   4.0   
12                                    Bonnell, Miss. Elizabeth  female  58.0   
13                              Saundercock, Mr. William Henry    male  20.0   
14                                 Andersson, Mr. Anders Johan    male  39.0   
15                        Vestrom, Miss. Hulda Amanda Adolfina  female  14.0   
16                            Hewlett, Mrs. (Mary D Kingcome)   female  55.0   
17                                        Rice, Master. Eugene    male   2.0   
18                                Williams, Mr. Charles Eugene    male   NaN   
19           Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0   
20                                     Masselmani, Mrs. Fatima  female   NaN   
21                                        Fynney, Mr. Joseph J    male  35.0   
22                                       Beesley, Mr. Lawrence    male  34.0   
23                                 McGowan, Miss. Anna "Annie"  female  15.0   
24                                Sloper, Mr. William Thompson    male  28.0   
25                               Palsson, Miss. Torborg Danira  female   8.0   
26           Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female  38.0   
27                                     Emir, Mr. Farred 

In [88]:
data['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [59]:
data['Name']

PassengerId
1                                Braund, Mr. Owen Harris
2      Cumings, Mrs. John Bradley (Florence Briggs Th...
3                                 Heikkinen, Miss. Laina
4           Futrelle, Mrs. Jacques Heath (Lily May Peel)
5                               Allen, Mr. William Henry
                             ...                        
887                                Montvila, Rev. Juozas
888                         Graham, Miss. Margaret Edith
889             Johnston, Miss. Catherine Helen "Carrie"
890                                Behr, Mr. Karl Howell
891                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [41]:
data['Age'].sum() / 714

29.69911764705882

In [66]:
data_fem = data[data.Sex == 'female']['Name']

In [68]:
result = {}

In [87]:
data2 = data[data.Sex == 'female']['Name']


C = []
for i in data2:
    if '(' in i:
        if ')' in i.split('(')[1].split(' ')[0]:
            C.append(i.split('(')[1].split(' ')[0].split(')')[0])
        else:
            C.append(i.split('(')[1].split(' ')[0])

    else:
        C.append(i.split('. ')[1].split(' ')[0])

print (pd.DataFrame.from_dict(C)[0].value_counts())

Anna         15
Mary         14
Elizabeth    11
Margaret     10
Alice         6
             ..
Virginia      1
Stella        1
Katie         1
Edwiga        1
Laura         1
Name: 0, Length: 178, dtype: int64
